### ISSUE TITLE
Необходимо изменить (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#10]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/f5fc9969a948cd71ab09f2b984b1c2d4a7bbc464/Lesson6/Math.cs#L3-L23
В этой задаче необходимо не выводить в консоль в самих методах, а возвращать значения, например, double

**Comment by Lyubov18** [comment]
" При передаче в методы двух числовых параметров нужно производить с параметрами соответствующие действия и печатать ответ." 
Формулировка печатать ответ в моем понимании соответствует печати ответа в консоли, а не возвращению результата.

**Comment by chiki-takipavel** [comment]
На одном из занятий для этой задачи было оговорено, что лучше возвращать значение, а не использовать метод для реализации двух различных действий, а уже затем в методе Main выводить результат.
