### ISSUE TITLE
Use collection (List, for example) instead of array (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#14]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/f5fc9969a948cd71ab09f2b984b1c2d4a7bbc464/Lesson8/Warehouse.cs#L5

**Comment by Lyubov18** [comment]
В условии задачи не сказано чем конкретно пользоваться, кроме ограничений на LINQ. Условию задачи мое решение соответствует, значит исправление должно быть не required. 
Аналогично с проблемой #15

**Comment by chiki-takipavel** [comment]
1. В условии задачи написано "список", а не "массив".
2. К данному занятию мы уже изучили различные коллекции. В этой задаче оптимальнее использовать список вместо массива.
