### ISSUE TITLE
Need to remove client from _passengersSurnames (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#17]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/f5fc9969a948cd71ab09f2b984b1c2d4a7bbc464/Lesson8/Bus.cs#L143-L168

**Comment by Lyubov18** [comment]
По условию для меня спорный момент с _passengersSurnames. В условии четкого описания на этот счет не было. Если в этой переменной хранить только фамилии пассажиров, находящихся в автобусе в текущий момент времени, то чем эта переменная будет отличаться от _busSeats.Values? Я подумала, что больший смысл имеет место переменная, в которой будут храниться фамилии всех пассажиров, которые ездили или едут на данном автобусе.

**Comment by chiki-takipavel** [comment]
Некоторые аспекты ТЗ могут быть указаны с целью реализации "наперёд" (для дальнейшего использования). В таком случае, если вы не видите оптимального использования этих аспектов в своём коде на данный момент, то можете или не обрабатывать их совсем, или обрабатывать полностью. В вашем случае при посадке пассажира вы добавляете его фамилию в список, а значит уже начинаете его обрабатывать.
