### ISSUE TITLE
Optimized solution (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#4]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/e99e764bdd97c9fbefbe0bee4373e5e9ef73c75f/Lesson4/Program.cs#L112
Good solution, but there is a better one - sort the array and compare elements one after another, counting the number of identical ones (just one loop).

**Comment by Lyubov18** [comment]
added solution with sorting and one loop
