### ISSUE TITLE
Can be optimized (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#5]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/6874be81aefc870d86e91a3263b7bade8296ee70/Lesson5/Program.cs#L249-L270
В шифровании и дешифровании можно убрать эту часть и оставить ту, что в ветке undefined, тогда у вас будет работать для строки, в которой и русский, и английский язык (alphabethType тоже нужно убрать)

**Comment by Lyubov18** [comment]
Я думала, что в задаче нужно понять какой алфавит и зашифровать только символы конкретного языка, игнорируя символы на другом языке и любые другие

**Comment by Lyubov18** [comment]
В задаче указано "Строка может состоять или из символов русского алфавита, или английского."
То есть если вводится текст на русском, то по моему решению до появления первого символа на русском символы будут проходить 2 проверки, и при первом появлении символа на русском создается одна дополнительная переменная и происходит только одна проверка до конца строки. С английским аналогично.
Если оставить только ту часть, что в ветке undefined, то мы избавимся от лишней переменной, но каждый символ будет проходить 1 или 2 проверки на всей строке. Если текст окажется на английском, то количество операций будет меньше (на количество первых символов не соответствующих алфавитам) или равным количеству операций в моем решении, а если текст окажется на русском, то  всегда будет по 2 проверки на каждый символ. Плюс в обоих случаях будет вызываться дважды для каждого символа метод IndexOf(). В моем методе он дважды вызывается только до появления первого алфавитного символа. 
Поэтому я не думаю, что часть функции из undefined будет более оптимизированной и корректной для поставленной задачи из-за того, что текст должен быть либо на одном, либо на другом языке, но не смешанным
