### ISSUE TITLE
Exception was thrown (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#6]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/6874be81aefc870d86e91a3263b7bade8296ee70/Lesson5/Program.cs#L119-L120
Программа завершается с ошибкой, если строка содержит только одну букву h. Также, можно оптимизировать, например, с помощью char[].

**Comment by Lyubov18** [comment]
У меня стоит проверка на длину строки, этот фрагмент кода в замечании отрабатывает только если строка от трех и более символов. Если менее трех, то вообще ничего с введенной строкой не делается, она выводится в первоначальном виде

**Comment by Lyubov18** [comment]
Исправила
