### ISSUE TITLE
There is no check for the radius value (greater than 0) (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#7]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/46837bdf135e94902f8adc7613a42a4b89dd31f2/Lesson7/Sphere.cs#L11-L15

**Comment by Lyubov18** [comment]
изменила set метод

**Comment by Lyubov18** [comment]
changed
