### ISSUE TITLE
Better to change (required)

### ISSUE THREAD

**Issue by chiki-takipavel** [Lyubov18/homework_itacademy_c_sharp#9]
https://github.com/Lyubov18/homework_itacademy_c_sharp/blob/46837bdf135e94902f8adc7613a42a4b89dd31f2/Lesson7/Sphere.cs#L47-L56
Выделите расстояние от центра до точки в отдельную переменную, а затем `return distance <= _radius * _radius;`

**Comment by Lyubov18** [comment]
я оставила переменную расстояние в квадрате - не хотелось использовать библиотеку Math для извлечения корня

**Comment by chiki-takipavel** [comment]
Здесь использование Math не понадобится, просто лучше вынести то, что находится до <, в отдельную переменную, а затем написать, например, `return squareDistance <= _radius * _radius;`. Так как конструкцию
```(csharp)
if (someCondition)
{
    return true;
}
else
{
    return false;
}
```
лучше упрощать до `return someCondition;`
